# See all rules by running Pods/SwiftLint/swiftlint rules
# Full details at https://github.com/realm/SwiftLint

included:
    - TrueDepthFusion
excluded:
    - Dependencies
disabled_rules:
    - block_based_kvo
    - comma
    - discarded_notification_center_observer
    - file_length
    - force_cast
    - force_try
    - function_body_length
    - function_parameter_count
    - identifier_name
    - line_length
    - opening_brace
    - operator_whitespace
    - todo
    - trailing_comma
    - trailing_whitespace
    - type_body_length
    - unused_closure_parameter
    - vertical_whitespace
    - weak_delegate
opt_in_rules:
    - array_init
